# Generated by Django 3.2.7 on 2021-10-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_auto_20211013_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='artwork_colour',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
