# Generated by Django 3.2.7 on 2021-09-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(blank=True, max_length=254, null=True)),
                ('artwork_request', models.CharField(blank=True, max_length=254, null=True)),
                ('product_size', models.CharField(max_length=254)),
                ('product_text_content', models.TextField()),
                ('artwork_colour', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
