# Generated by Django 3.2.7 on 2021-09-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='artwork_colour',
            field=models.CharField(choices=[('full_colour', 'Full Colour'), ('black_white', 'Black & White')], default='full_colour', max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='artwork_request',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_size',
            field=models.CharField(choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('A6', 'A6')], default='A4', max_length=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_text_content',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
