# Generated by Django 3.2.7 on 2021-10-03 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0002_auto_20210929_1518'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
