# Generated by Django 3.2.7 on 2021-10-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
