# Generated by Django 3.2.7 on 2021-10-05 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_custom_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='custom_cost',
        ),
    ]
